# Generated by Django 5.0.2 on 2024-03-03 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CvCreate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('father_name', models.CharField(max_length=25)),
                ('mother_name', models.CharField(max_length=25)),
                ('email', models.EmailField(blank=True, max_length=30, null=True)),
                ('phone', models.CharField(max_length=15)),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'MALE'), ('Female', 'FEMALE'), ('Others', 'OTHERS')], default='MALE', max_length=6)),
                ('present_address', models.CharField(blank=True, max_length=100, null=True)),
                ('permanent_address', models.CharField(blank=True, max_length=100, null=True)),
                ('exam_name1', models.CharField(blank=True, max_length=50, null=True)),
                ('exam_board1', models.CharField(blank=True, max_length=15, null=True)),
                ('exam_passingyear1', models.CharField(blank=True, max_length=4, null=True)),
                ('exam_result1', models.CharField(blank=True, max_length=3, null=True)),
                ('exam_name2', models.CharField(blank=True, max_length=50, null=True)),
                ('exam_board2', models.CharField(blank=True, max_length=15, null=True)),
                ('exam_passingyear2', models.CharField(blank=True, max_length=4, null=True)),
                ('exam_result2', models.CharField(blank=True, max_length=3, null=True)),
                ('exam_name3', models.CharField(blank=True, max_length=50, null=True)),
                ('exam_board3', models.CharField(blank=True, max_length=15, null=True)),
                ('exam_passingyear3', models.CharField(blank=True, max_length=4, null=True)),
                ('exam_result3', models.CharField(blank=True, max_length=3, null=True)),
                ('exam_name4', models.CharField(blank=True, max_length=50, null=True)),
                ('exam_board4', models.CharField(blank=True, max_length=15, null=True)),
                ('exam_passingyear4', models.CharField(blank=True, max_length=4, null=True)),
                ('exam_result4', models.CharField(blank=True, max_length=3, null=True)),
                ('experience', models.CharField(blank=True, max_length=150, null=True)),
                ('extra_curriculam', models.CharField(blank=True, max_length=150, null=True)),
                ('training_name', models.CharField(blank=True, max_length=50, null=True)),
                ('training_company', models.CharField(blank=True, max_length=50, null=True)),
                ('training_duration', models.CharField(blank=True, max_length=50, null=True)),
                ('training_achevment', models.CharField(blank=True, max_length=50, null=True)),
                ('training_place', models.CharField(blank=True, max_length=50, null=True)),
                ('career_object', models.CharField(blank=True, max_length=150, null=True)),
                ('declaration', models.CharField(blank=True, max_length=250, null=True)),
                ('image', models.ImageField(blank=True, default='def.jpg', null=True, upload_to='image/')),
            ],
        ),
    ]
